### PR TITLE
Switch from drone.io to travis-ci.org links

### PR DESCRIPTION
**Pull request by gregturn**

### CODE REVIEW

**Comment by gregturn** [comment]
When this is merged, can we clean out the Redis cache to cleanly rebuild it?

**Comment by bclozel** [comment]
Sure!
It looks like some tests are failing - could you fix those first?

**Comment by gregturn** [comment]
@bclozel Okay, I fixed those test cases. :)

**Comment by bclozel** [comment]
Awesome, thanks!

**Comment by gregturn** [comment]
Any way we can wipe the redis cache after this gets deployed?

**Comment by bclozel** [comment]
I'll do that from the redislabs management console.
Thanks for the reminder.

**Pull request merged**
