### PR TITLE
Code snippets with tab size 4 by default

### PR DESCRIPTION
**Pull request by BoykoAlex**
Came out as the result of the conversation here: https://pivotal.slack.com/archives/C064D3HPZ/p1574414987039400

### CODE REVIEW

**Comment by dsyer** [comment]
LGTM. We might even want to go down to 2 spaces?

**Comment by gregturn** [comment]
What happens if you use tabsize? Does it override this CSS?

**Comment by BoykoAlex** [comment]
Yes, if you use `tabsize` in your MD it'd override the CSS.

**Comment by dsyer** [comment]
In the asciidoc you mean? Yes, it overrides, or rather invalidates the CSS, since it just formats everything with spaces. In the light if the accessibility argument, that probably means we should translate all guides to tabs.

**Comment by BoykoAlex** [comment]
The asciidoc - correct.

**Comment by gregturn** [comment]
Thanks Dave. That is my plan regarding the guides.

**Pull request merged**
