### PR TITLE
Adds exception handler for HttpSatusCodeExceptions

### PR DESCRIPTION
**Pull request by jjsfernandez**
fixes error when it returns 500 instead of 404 when requesting a guide or topical that doesn't exist, fixes issue #933

### CODE REVIEW

**Comment by JosejeSinohui** [comment]
@snicoll Hi!, any follow up on this?

**Comment by bclozel** [comment]
Sorry I didn’t have time yet to fully review this.
At a first glance, I’m not happy about mapping client exceptions to server exceptions directly.
Could you instead catch the client exception in the service directly and wrap it with a ResourceNotFoundException instead? This will be mapped as a 404 automatically. Also, an additional test in that service layer would be nice, but I can take care of it if it’s hard to figure out.
Thanks!

**Comment by JosejeSinohui** [comment]
I can keep working on this, i'm just unsure what the "service" layer is in this case. 
The controllers (ex: https://github.com/spring-io/sagan/blob/master/sagan-site/src/main/java/sagan/site/guides/GettingStartedGuideController.java).
Use the repository components (ex: https://github.com/spring-io/sagan/blob/master/sagan-site/src/main/java/sagan/site/guides/GettingStartedGuides.java). Which in turn uses 
 sagan renderer client(https://github.com/spring-io/sagan/blob/master/sagan-site/src/main/java/sagan/site/renderer/SaganRendererClient.java). this is where the exception is thrown.

I tried adding an exception handler on the renderer client class but it doesn't pick up the exceptions.

The following does handle the exception and returns a 404 but it doesn't render the 404 page. And it would also have to be added to every method. 
```
public GuideMetadata fetchGettingStartedGuide(String name) {
	try{
		return this.traverson.follow("guides")
				.follow(Hop.rel("getting-started").withParameter("guide", name))
				.toObject(GuideMetadata.class);
	}catch(HttpStatusCodeException ex){
		if (ex.getStatusCode() == HttpStatus.NOT_FOUND) {
			throw new ResourceNotFoundException(name + " not found");
		}
		throw ex;
	}
}
```

is this the right approach or am I still missing something?

**Comment by bclozel** [comment]
`SaganRendererClient ` feels like the right place at a quick glance, but we might change our mind along the way. You can follow that approach and see where it leads you.
As for the 404 template, I can look into that - getting a proper 404 is a good first step. Thanks!

**Comment by JosejeSinohui** [comment]
@bclozel I made the requested changes, now it correctly returns a 404 response, but still doesn't render the template.

**Comment by shifajaman** [comment]
i will work on this.

**Pull request closed without merging**
