### PR TITLE
Add End of Life management to project management

### PR DESCRIPTION
**Pull request by gregturn**
This adds a new field to the ProjectRelease entity and makes it possible to manage this value on /admin/project page.

### CODE REVIEW

**Comment by gregturn** [comment]
@bclozel This PR adds the ability to assign a string-based end of life value (a date or a version of Spring) to each project's release version. It also adds a new EOL page under the /admin page, allowing a one-page glance at ALL EOL dates.

This is to support @dussab 's request for a means for project leads to enter EOL details on a per-project/per-release basis and easily distribute it out to the project pages via sagan's metadata.

I will also write an update to the project page templates that uses this information once this PR is merged to master and deployed.

**Comment by bclozel** [comment]
Pinging @snicoll since start.spring.io is using project metadata - do you think there'd be a way to leverage that in start.spring.io? Would a different format help?

**Comment by snicoll** [comment]
We only use that for Spring Boot at the moment (to get the latest versions for the version picker). The way we treat with EOL on start.spring.io is via a range for the Spring Boot versions. Let's say Spring Foo is EOL next year, then it won't have any integration with the next version of Spring Boot and it will be disabled long before it is actually EOL.

Am I missing something?

**Comment by bclozel** [comment]
@snicoll No, LGTM.

Now I'm wondering if we should actually put more constraints on the EOL format.
Right now it's just text and it's up to the client to parse and figure things out. We could have two fields, one with the supported spring framework version and another as a date. We could only expose the EOL date field and derive it from the framework version if present.

WDYT @gregturn ?

**Comment by gregturn** [comment]
I was trying to avoid any complex entanglements and let project leads pick what is suitable for their community. A simple text field sounded like it. Adding dates and dependencies sounds complex and more likely to be wrong rather than right. If we need something more intricate, we could develop it. But if this is suitable for present needs, it won't soak up any more time from anyone.

**Comment by snicoll** [comment]
What is the semantic of the field then? Raw text to be displayed to the user? I am not sure that's the right call for something that should/might display a date. If that's a date, what's wrong with constraint it to that?

**Comment by gregturn** [comment]
The semantic is that for each version, the project lead can list either a date or a specific something else that it will be supported.

For example "Spring Data Kay-RELEASE" could cite "Spring Boot 2.0".

For Spring Web Services, I plan to put "Spring Framework 4.2.x".

**Comment by bclozel** [comment]
We're working on a different take for this feature. I'm closing this PR now.
Thanks for your help!

**Pull request closed without merging**
