### PR TITLE
Fix tests when default Locale is not US

### PR DESCRIPTION
**Pull request by pintiliea**
Fix for #624

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pintiliea Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/sagan&pullRequestId=688)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-io/sagan&pullRequestId=688) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@pintiliea Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/sagan&pullRequestId=688)!

**Comment by dsyer** [comment]
IMO it would be better to actually set the locale in the test, so that we have a stable build without any messing about by the developer.

**Comment by pintiliea** [comment]
@dsyer Look at the test and you'll see it already does that. It set's Locale.US in the @Before method and resets it back to the default locale in the @After method.

The problem is the static modifier of that SimpleDateFormat class variable. If you run that test class it will pass all tests. If you run the tests at the package level (or the whole build) it will fail.

Try it and see for your self.

Regards

**Comment by dsyer** [comment]
Ah, OK. Seems like a good change then.

**Comment by bclozel** [comment]
Thanks!

**Pull request merged**
