### PR TITLE
Update hub usage example

### PR DESCRIPTION
**Pull request by muRn**
pull-request is hub's command, not git's. Example was wrong.
More examples of using `hub pull-request` from hub documentation: https://hub.github.com/hub-pull-request.1.html

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@muRn Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/sagan&pullRequestId=997)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-io/sagan&pullRequestId=997) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@muRn Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/sagan&pullRequestId=997)!

**Comment by dsyer** [comment]
Many (most) hub users alias it to "git". I guess we could mention that instead?

**Comment by muRn** [comment]
Didn't know about that, sorry. I can add something like
```
# or, if you alias hub to git as most hub users do
git pull-request -i 123
```
in the end. Will that be ok?

Or would it be better to just roll back the example back to git and add a comment like
```
# will work if you alias hub to git
```
or
```
# don't forget to alias hub to git
```

**Comment by dsyer** [comment]
LGTM

**Pull request merged**
