### PR TITLE
Update SCDF tagline and product features

### PR DESCRIPTION
**Pull request by sabbyanandan**
Spring Cloud Data Flow's product focus and the message had evolved; however, the current description on the homepage is extremely dated, and it needs an update.  

I would like to update the product messaging and feature-set, so it is consistent with how we present, including at Pivotal's [Spring](https://pivotal.io/spring-app-framework) site.

### CODE REVIEW

**Comment by bclozel** [comment]
Hey @sabbyanandan , thanks for the update!
This PR removes the `monitor.jpg` image, because I guess the UI is outdated. But it's not replacing it with a more recent version of it.
Merging this means we'd get HTTP 404s and the homepage would be missing an image (which was part of the design intent there). Could you get an updated version of this image instead?

Thanks!

**Comment by sabbyanandan** [comment]
Thanks for the review, @bclozel. I updated with a higher resolution image; however, the dashboard screenshot is not overlayed on top of the monitor background. If that is indeed a preferred variant, I'm happy to get that figured out. Let me know.

**Comment by sabbyanandan** [comment]
Hi, @bclozel. Any further thoughts here?

**Comment by bclozel** [comment]
This is now out of date, as the homepage has been redesigned since.

**Pull request closed without merging**
