### PR TITLE
Revisit Search features: indexation and queries

### PR DESCRIPTION
**Pull request by bclozel**
This commit improves search in Sagan in many ways and tries to address
several search problems (relevance, filtering, etc).

First, dependencies have been upgraded to Jest 0.1.6
and ElasticSearch 1.5.2, which include many changes in ES's API since
0.90.x versions.

ES index settings and type mappings have been completely revisted; now
search entries are organized in 5 types: apidoc, sitepage, referencedoc,
guidedoc and blogpost. Each type has specific properties but they all
share common properties described in `SearchEntry`.
This allows to narrow down searches with types, more fine grained
mappings configurations and avoid unnecessary null/default values
in properties.
Type mappings and settings have been modified to better index entries
and support search patterns (see `apidoc.json` and others).

The main search query has been improved, with fuzziness support in the
`multi_match` query, more fine grained filters to avoir unpublished
entries in search results, a better sort algorithm (score + publication
date if available). A complete query example can be found in
`fulltext-query.json`.

Instead of relying on a external ElasticSearch instance, this commit
makes use of a Marketplace service on PWS. See `SearchClientConfig`.
In order to auto-detect this service, a new Spring Cloud Connector
`ElasticSearchServiceInfoCreator` has been created.
This class should be reoved as soon as this is supported in the
offical project.

Fixes #421 #274 #387 #449 #429

### CODE REVIEW

**Comment by cbeams** [comment]
Cool! I look forward to trying this once it's merged :)

**Comment by bclozel** [comment]
Hey Chris!
There's still room for improvement - especially some boost factors and fuzziness parameters that can be tweaked. Luckily Searchly provides an analytics page where I'll see stats about frequent search terms; I'll work from there with the Spring team to tweak the results!

**Comment by gregturn** [comment]
@cbeams Does this mean your baby is all grown up?

**Comment by bclozel** [comment]
This is now live - indexing is still in progress at the moment.

**Pull request merged**
